"""init db

Revision ID: 06997b8fd623
Revises: 1f4a3eee3c90
Create Date: 2025-05-20 18:14:06.688472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06997b8fd623'
down_revision: Union[str, None] = '1f4a3eee3c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fitness_data', 'weight',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('fitness_data', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('fitness_data', 'gender',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('fitness_data', 'goal',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('fitness_data', 'activity_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('fitness_data', 'plan',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_fitness_data_id'), 'fitness_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fitness_data_id'), table_name='fitness_data')
    op.alter_column('fitness_data', 'plan',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fitness_data', 'activity_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fitness_data', 'goal',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fitness_data', 'gender',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fitness_data', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fitness_data', 'weight',
               existing_type=sa.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###
